### ISSUE TITLE
GHC-8.6.1: base-4.12 / template-haskell-2.14

### ISSUE THREAD

**Issue by phadej** [haskell-infra/hackage-trustees#166]
This is issue is for now to collect packages, we suspect has versions which advertise they are compatible, but in fact aren't. As GHC-8.6 is in early alpha, we shouldn't do anything yet, as things may change.

*Note* we have to be accurate, as some packages may be "guarded" by other packages without GHC-8.6 compatible release (e.g. `hashable` guards `constraints`).

containers-0.6 has own issue: https://github.com/haskell-infra/hackage-trustees/issues/164, but they manifest itself only on GHC-8.6, either issue is ok to report.

- [x] basement (0.0.4 ... 0.0.7)
- [x] constraints (at least 0.10, seems 0.9 is broken with GHC-8.4.3, needs `--allow-newer=hashable:base`,*note* it's not `base` issue, but GHC changing things. Unfortunate situation, no-one can be blamed for that, i.e. StarIsType` related things)
- [x] stm (older releases)
- [x] tasty (`Ambiguous occurrence ‘Ap’`)
- [x] memory (based on https://github.com/hvr/head.hackage/pull/64)
- [x] reflection (based on https://github.com/hvr/head.hackage/pull/64)
- [x] superrecord

From the comment https://github.com/haskell-infra/hackage-trustees/issues/166#issuecomment-403544256
* GHC 8.6 language extension changes, improper upper version bounds on `base`
  * `StarIsType` breakage
    * [x] `exact-pi-0.4.1.3`
    * [x] `numtype-dk-0.5.0.1`
  * `UndecidableInstances` is pickier
    * [x] `vector-space-0.13`
* Breaks with `base-4.12`, improper upper version bounds on `base`
  * [x] `tasty-1.1.0.2`
* Breaks with `unix-2.8`, improper upper version bounds on `unix`, **invalid** `unix-2.8` didn't happen
  * [x] `acid-state-0.14.3`
  * [x] `bytestring-mmap-0.2.2`
  * [x] `crypto-random-0.0.9`
  * [x] `entropy-0.4.1.1`
  * [x] `filelock-0.1.1.2`
  * [x] `shake-0.16.4`
  * [x] `simple-sendfile-0.2.27`
  * [x] `snap-server-1.1.0.0`
  * [x] `Unixutils-1.54.1`
  * [x] `warp-3.2.22` and `warp-3.2.23`

More libs:

* [x] `c2hs-0.28.5`
* [x] `graphviz-2999.20.0.2`
* [x] `gtk2hs-buildtools-0.13.4.0`
* [x] `haskell-src-exts-1.20.2`
* [x] `pandoc-2.2.2.1`
* [x] `polyparse-1.12`
* [x] `texmath-0.11.0.1`
* [x] `yi-core-0.18.0`
* [x] `yi-keymap-emacs-0.18.0`
* [x] `yi-keymap-vim-0.18.0`
* [x] `yi-mode-javascript-0.18.0`
* [x] `xmonad-0.14`

From #164

* [x] `ixset-1.1` (guarded by syb-with-class; will break)
* [x] `ixset-typed-0.4` (not an issue, there is template-haskell <4.12 bound)
* [x] `language-c-0.8.1`
* [x] `multiset-0.3.4`
* [x] `patience-0.1.1`

The rest is from https://github.com/haskell-infra/hackage-trustees/issues/135, that should be checked (may fail with GHC-8.4 too):

- [x] formatting-6.3.0 (chrisdone/formatting#34)
- [x] hashtables-1.2.2.1 (gregorycollins/hashtables#47 and gregorycollins/hashtables#46)
- [x] haskell-src-exts-1.20.1 (haskell-suite/haskell-src-exts#397)
- [x] inline-c-0.6.0.5 (fpco/inline-c#66)
- [x] language-java-0.2.8 (vincenthz/language-java#63)
- [x] language-javascript-0.6.0.10 (erikd/language-javascript#65)
- [x] llvm-hs-5.1.3
- [x] llvm-hs-pure-5.1.2 (llvm-hs/llvm-hs#175)
- [x] map-syntax-0.2.0.2 (mightybyte/map-syntax#11)
- [x] monadplus-1.4.2 (hanshoglund/monadplus#3)
- [x] simple-reflect-0.3.2 (twanvl/simple-reflect#2)
- [x] snap-server-1.0.3.3 (snapframework/snap-server#106)
- [x] streaming-0.2.0.0 (haskell-streaming/streaming#35)
- [x] vinyl-0.7.0
- [x] websockets-0.12.3.1 (jaspervdj/websockets#164)

**Comment by RyanGlScott** [comment]
I'm guessing that every release of `reflection` back until version 1.3 (the first release to use the quoted Template Haskell name `''(*)`) will need to have its upper version bounds on `base` revised to `< 4.12`? If so, let me know and I'll do this.

**Comment by phadej** [comment]
No worries, I could make mass-edits. Do you want them sooner? (I'd wait till my proposal is officially approved)

**Comment by RyanGlScott** [comment]
Great! No hurry on my end, I just happened to be mucking with `reflection` at the time and remembered of this issue's existence.

**Comment by RyanGlScott** [comment]
Here's some more issues I've uncovered in hvr/head.hackage#51, hvr/head.hackage#52, hvr/head.hackage#53, hvr/head.hackage#54, hvr/head.hackage#55, hvr/head.hackage#56, hvr/head.hackage#57, hvr/head.hackage#59, hvr/head.hackage#60, hvr/head.hackage#68, and hvr/head.hackage#70, roughly categorized by how they're failing:

* GHC 8.6 language extension changes, improper upper version bounds on `base`
  * `StarIsType` breakage
    * [ ] `exact-pi-0.4.1.3`
    * [ ] `numtype-dk-0.5.0.1`
  * `UndecidableInstances` is pickier
    * [ ] `vector-space-0.13`
* Breaks with `base-4.12`, improper upper version bounds on `base`
  * [ ] `tasty-1.1.0.2`
* Breaks with `unix-2.8`, improper upper version bounds on `unix`
  * [ ] `acid-state-0.14.3`
  * [ ] `bytestring-mmap-0.2.2`
  * [ ] `crypto-random-0.0.9`
  * [ ] `entropy-0.4.1.1`
  * [ ] `filelock-0.1.1.2`
  * [ ] `shake-0.16.4`
  * [ ] `simple-sendfile-0.2.27`
  * [ ] `snap-server-1.1.0.0`
  * [ ] `Unixutils-1.54.1`
  * [ ] `warp-3.2.22`

**Comment by RyanGlScott** [comment]
Here's some more packages to add to the list (taken from https://github.com/hvr/head.hackage/commit/3c15fe8766d1619f71f201ce086fe4602104d14b and hvr/head.hackage#79). This time, it's packages that break under `MonadFailDesugaring` and have improper upper version bounds on `base`:

* [ ] `c2hs-0.28.5`
* [ ] `graphviz-2999.20.0.2`
* [ ] `gtk2hs-buildtools-0.13.4.0`
* [ ] `haskell-src-exts-1.20.2`
* [ ] `pandoc-2.2.2.1`
* [ ] `polyparse-1.12`
* [ ] `texmath-0.11.0.1`
* [ ] `yi-core-0.18.0`
* [ ] `yi-keymap-emacs-0.18.0`
* [ ] `yi-keymap-vim-0.18.0`
* [ ] `yi-mode-javascript-0.18.0`
* [ ] `xmonad-0.14`

**Comment by hvr** [comment]
@quasicomputational thanks for telling us! I've just revised the 4 affected releases of `criterion` accordingly

**Comment by phadej** [comment]
Made own issue for yi-packages : https://github.com/haskell-infra/hackage-trustees/issues/177

**Comment by phadej** [comment]
Everything to seems to be green (for recent releases). I'm closing this issue. If new broken things arise, please open separate issues.
